CREATE TABLE chats
(
    id         UUID         NOT NULL,
    title      VARCHAR(255) NOT NULL,
    status     VARCHAR(255) NOT NULL,
    user_id    UUID         NOT NULL,
    persona_id BIGINT       NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_chats PRIMARY KEY (id)
);

CREATE TABLE messages
(
    id          BIGINT       NOT NULL,
    user_id     UUID         NOT NULL,
    sender_type VARCHAR(255) NOT NULL,
    content     TEXT         NOT NULL,
    timestamp   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_messages PRIMARY KEY (id)
);

CREATE TABLE personas
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          VARCHAR(255)                            NOT NULL,
    system_prompt TEXT                                    NOT NULL,
    type          VARCHAR(255)                            NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_personas PRIMARY KEY (id)
);

CREATE TABLE users
(
    id         UUID         NOT NULL,
    email      VARCHAR(255) NOT NULL,
    name       VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE chats
    ADD CONSTRAINT FK_CHATS_ON_PERSONA FOREIGN KEY (persona_id) REFERENCES personas (id);

ALTER TABLE chats
    ADD CONSTRAINT FK_CHATS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE messages
    ADD CONSTRAINT FK_MESSAGES_ON_USER FOREIGN KEY (user_id) REFERENCES chats (id);